name: Publish Package

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          # Setup .npmrc file to publish to npm
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_VIMEO_PUBLISH_TOKEN }}
